#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App.Resource", IsApplication=true)]

namespace App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alert = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bell = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int call = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cross1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int msg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int msg2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int msg3 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int msg4 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int tick = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int tick2 = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int Start_ALarm = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Stop_ALarm = 2131165185;
			
			// aapt resource value: 0x7f070009
			public const int TableGPS = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int button1 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int button2 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int button3 = 2131165198;
			
			// aapt resource value: 0x7f070002
			public const int cancelButton = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int contacts = 2131165188;
			
			// aapt resource value: 0x7f070017
			public const int imageView1 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int item1 = 2131165208;
			
			// aapt resource value: 0x7f070008
			public const int mediaController1 = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int name1 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int name2 = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int relativeLayout1 = 2131165194;
			
			// aapt resource value: 0x7f070003
			public const int saveButton = 2131165187;
			
			// aapt resource value: 0x7f07000f
			public const int showPopup = 2131165199;
			
			// aapt resource value: 0x7f070016
			public const int surfaceView1 = 2131165206;
			
			// aapt resource value: 0x7f07000b
			public const int tableRow10 = 2131165195;
			
			// aapt resource value: 0x7f070011
			public const int tableRow11 = 2131165201;
			
			// aapt resource value: 0x7f070005
			public const int tableRow12 = 2131165189;
			
			// aapt resource value: 0x7f070012
			public const int textView3 = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int textView4 = 2131165204;
			
			// aapt resource value: 0x7f070010
			public const int txtDateTimeAndProvider = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int txtLatitude = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int txtLongitude = 2131165205;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int alarm = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int contacts = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int pics = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int Main = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int police_alarm = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int cancelButton = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int saveButton = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int txt_latitude = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int txt_longitude = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
